### ISSUE TITLE
How to get to admin panel?

### ISSUE THREAD

**Issue by Geckis** [jbouzekri/free-bet#8]
hi, can u tell me how to get to admin page?

**Comment by jbouzekri** [comment]
I am deeply sorry. I have just seen your issue (I never received any notification).

Just in case, I am going to answer : 

You login with a user having administrator role. It will unlock some features on different pages to create and/or edit events, bets, ...

In my demo, login using admin/admin and after that for example on this page : https://free-bet.bouzekri.net/premiere-league-2014 you can see the button "set result" only available to admin.
