### ISSUE TITLE
how to add a match

### ISSUE THREAD

**Issue by aminvakil** [jbouzekri/free-bet#9]
i've been looking through your admin demo panel and i didn't find any button, command, etc. to add a match.

can you help me?

**Comment by jbouzekri** [comment]
You are right, I have not implemented the "add a match" button.

But you can create a full competition using the import data fixtures feature :

https://github.com/jbouzekri/free-bet/blob/master/src/FreeBet/Bundle/SoccerWorldCupBundle/DataFixtures/MongoDB/LoadCompetitionData.php
https://github.com/jbouzekri/free-bet/blob/master/src/FreeBet/Bundle/SoccerWorldCupBundle/DataFixtures/MongoDB/LoadMatchData.php
https://github.com/jbouzekri/free-bet/blob/master/src/FreeBet/Bundle/SoccerWorldCupBundle/Resources/data/match.csv

with the command : 

```
php app/console doctrine:mongodb:fixtures:load
```
